name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8
    
    - name: Run Black
      run: black --check --line-length=99 plugin/
    
    - name: Run isort
      run: isort --check-only --profile=black --line-length=99 plugin/
    
    - name: Run flake8
      run: flake8 plugin/ --max-line-length=99 --extend-ignore=E203,W503

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-mock
        pip install -r requirements.txt || true
    
    - name: Run tests
      run: |
        pytest tests/ -v || echo "No tests found yet"

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install maubot
      run: |
        python -m pip install --upgrade pip
        pip install maubot
    
    - name: Build plugin
      run: |
        cd plugin
        zip -r ../matrix-to-discourse.mbp *
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: matrix-to-discourse-plugin
        path: matrix-to-discourse.mbp 